# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: whitty@github
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  notes on coding with a bent toward embedded.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://whitty.github.io" # the base hostname & protocol for your site
github_username:  whitty

# Build settings
markdown: kramdown

exclude: ['Gemfile.lock', 'Gemfile']

# Be like github (and allow cache:false below to work)
safe: true

sass:
    style: compressed
    cache: false
